Repository KOSA-MOJI/MOJI, pull requests merged in 2024-09, with the labels that each got.

#9 [FEAT]: Diary read, write, edit page front
  src/main/java/com/spring/moji/controller/TestController.java
  src/main/resources/mapper/PageMapper.xml
  src/main/resources/static/css/content/diary/cover-diary.css
  src/main/resources/static/css/content/diary/read-diary.css
  src/main/resources/static/css/content/diary/write-diary.css
  src/main/resources/static/image/content/diary/001.png
  src/main/resources/static/image/content/diary/003.png
  src/main/resources/static/image/content/diary/004.png
  src/main/resources/static/image/content/diary/005.png
  src/main/resources/static/image/content/diary/006.png
  src/main/resources/static/image/content/diary/007.png
  src/main/resources/static/image/content/diary/center.png
  src/main/resources/static/image/content/diary/cover-spring.png
  src/main/resources/static/image/content/diary/cover-upload.png
  src/main/resources/static/image/content/diary/create-diary.png
  src/main/resources/static/image/content/diary/diary_start.png
  src/main/resources/static/image/content/diary/left.png
  src/main/resources/static/image/content/diary/right.png
  src/main/resources/static/image/content/diary/spring.jpg
  src/main/webapp/WEB-INF/jsp/content/diary/cover-diary.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/read-diary.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/write-diary.jsp
  src/main/webapp/WEB-INF/jsp/page/diary/cover-diary-page.jsp
  src/main/webapp/WEB-INF/jsp/page/diary/read-diary-page.jsp
  src/main/webapp/WEB-INF/jsp/page/diary/write-diary-page.jsp
Labels: 💫feature

#13 [DOCS] 테스트 DB 스키마 작성
  src/main/resources/SQL/shema.sql
Labels: ✨chore

#14 [Feature] 다이어리 페이지 작성 좌측 컴포넌트/로직 제작
  src/main/java/com/spring/moji/controller/TestController.java
  src/main/resources/static/js/content/diary/write-diary-left-component.js
  src/main/webapp/WEB-INF/jsp/content/diary/write-diary-left-component.jsp
  src/main/webapp/WEB-INF/jsp/content/user/solo-profile.jsp
  src/main/webapp/WEB-INF/jsp/page/diary/diary-page.jsp
Labels: 💫feature, FE

#19 Feat/15 be diary
  src/main/java/com/spring/moji/controller/DiaryController.java
  src/main/java/com/spring/moji/controller/DiaryRestController.java
  src/main/java/com/spring/moji/controller/TestController.java
  src/main/java/com/spring/moji/dto/request/DiaryRequestDTO.java
  src/main/java/com/spring/moji/entity/Diary.java
  src/main/java/com/spring/moji/mapper/DiaryMapper.java
  src/main/java/com/spring/moji/service/DiaryService.java
  src/main/java/com/spring/moji/service/DiaryServiceImpl.java
  src/main/java/com/spring/moji/service/ITestService.java
  src/main/java/com/spring/moji/service/TestService.java
  src/main/java/com/spring/moji/service/TestServiceImpl.java
  src/main/resources/mapper/DiaryMapper.xml
Labels: 💫feature, 😶‍🌫️ rename, BE

#21 [FEAT] 다이어리 조회 REST API 구현
  src/main/java/com/spring/moji/controller/ImageUrlRestController.java
  src/main/java/com/spring/moji/controller/LocationRestController.java
  src/main/java/com/spring/moji/controller/PageRestController.java
  src/main/java/com/spring/moji/controller/TemplateRestController.java
  src/main/java/com/spring/moji/dto/request/PageRequestDTO.java
  src/main/java/com/spring/moji/entity/ImageUrl.java
  src/main/java/com/spring/moji/entity/Location.java
  src/main/java/com/spring/moji/entity/Page.java
  src/main/java/com/spring/moji/entity/Template.java
  src/main/java/com/spring/moji/mapper/ImageUrlMapper.java
  src/main/java/com/spring/moji/mapper/LocationMapper.java
  src/main/java/com/spring/moji/mapper/PageMapper.java
  src/main/java/com/spring/moji/mapper/TemplateMapper.java
  src/main/java/com/spring/moji/service/DiaryServiceImpl.java
  src/main/java/com/spring/moji/service/ImageUrlService.java
  src/main/java/com/spring/moji/service/ImageUrlServiceImpl.java
  src/main/java/com/spring/moji/service/LocationService.java
  src/main/java/com/spring/moji/service/LocationServiceImpl.java
  src/main/java/com/spring/moji/service/PageService.java
  src/main/java/com/spring/moji/service/PageServiceImpl.java
  src/main/java/com/spring/moji/service/TemplateService.java
  src/main/java/com/spring/moji/service/TemplateServiceImpl.java
  src/main/resources/SQL/shema.sql
  src/main/resources/mapper/ImageUrlMapper.xml
  src/main/resources/mapper/LocationMapper.xml
  src/main/resources/mapper/PageMapper.xml
  src/main/resources/mapper/TemplateMapper.xml
Labels: 🖋️comment, 💫feature, 🔮 refactor, ⭐sytle, BE

#23 [FEAT] 북마크 조회 REST API 구현
  src/main/java/com/spring/moji/controller/BookmarkRestController.java
  src/main/java/com/spring/moji/entity/Bookmark.java
  src/main/java/com/spring/moji/mapper/BookmarkMapper.java
  src/main/java/com/spring/moji/service/BookmarkService.java
  src/main/java/com/spring/moji/service/BookmarkServiceImpl.java
  src/main/resources/SQL/shema.sql
  src/main/resources/mapper/BookmarkMapper.xml
Labels: 💫feature, 😶‍🌫️ rename, BE

#29 [FEAT]: combine diary component
  src/main/resources/static/js/content/diary/read-diary.js
  src/main/resources/static/js/content/diary/write-diary.js
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read-page.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/first-page.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/read-diary.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/second-page.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/template.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/toolbar.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/write-diary.jsp
  src/main/webapp/WEB-INF/jsp/page/diary/write-diary-page.jsp
Labels: 💫feature, FE

#31 [FEAT]: diary delete part
  src/main/java/com/spring/moji/controller/PageRestController.java
  src/main/java/com/spring/moji/mapper/PageMapper.java
  src/main/java/com/spring/moji/service/PageService.java
  src/main/java/com/spring/moji/service/PageServiceImpl.java
  src/main/resources/mapper/PageMapper.xml
Labels: 💫feature, BE

#33 [FEAT] 다이어리 조회 관련 REST API 구현
  src/main/java/com/spring/moji/controller/DiaryController.java
  src/main/java/com/spring/moji/controller/DiaryRestController.java
  src/main/java/com/spring/moji/controller/ImageUrlRestController.java
  src/main/java/com/spring/moji/controller/LocationRestController.java
  src/main/java/com/spring/moji/controller/PageRestController.java
  src/main/java/com/spring/moji/controller/TemplateRestController.java
  src/main/java/com/spring/moji/entity/Diary.java
  src/main/java/com/spring/moji/entity/Location.java
  src/main/java/com/spring/moji/entity/Page.java
  src/main/java/com/spring/moji/service/DiaryService.java
  src/main/java/com/spring/moji/service/DiaryServiceImpl.java
  src/main/resources/mapper/DiaryMapper.xml
  src/main/resources/mapper/PageMapper.xml
Labels: 🖋️comment, 💫feature, BE

#35 [Feat]: diary insert back
  src/main/java/com/spring/moji/controller/PageRestController.java
  src/main/java/com/spring/moji/dto/request/ImageUrlRequestDTO.java
  src/main/java/com/spring/moji/dto/request/LocationRequestDTO.java
  src/main/java/com/spring/moji/dto/request/PageInsertRequestDTO.java
  src/main/java/com/spring/moji/entity/Couple.java
  src/main/java/com/spring/moji/entity/Location.java
  src/main/java/com/spring/moji/entity/Role.java
  src/main/java/com/spring/moji/entity/User.java
  src/main/java/com/spring/moji/mapper/PageMapper.java
  src/main/java/com/spring/moji/service/PageService.java
  src/main/java/com/spring/moji/service/PageServiceImpl.java
  src/main/resources/SQL/deleteSchema.sql
  src/main/resources/SQL/totalSchema.sql
  src/main/resources/mapper/PageMapper.xml
Labels: 💫feature, BE

#37 [FIX]: unused responseDTO deteted
  src/main/java/com/spring/moji/controller/PageRestController.java
  src/main/java/com/spring/moji/mapper/ImageUrlMapper.java
  src/main/java/com/spring/moji/mapper/LocationMapper.java
  src/main/java/com/spring/moji/mapper/PageMapper.java
  src/main/java/com/spring/moji/service/PageService.java
  src/main/java/com/spring/moji/service/PageServiceImpl.java
  src/main/resources/mapper/ImageUrlMapper.xml
  src/main/resources/mapper/LocationMapper.xml
  src/main/resources/mapper/PageMapper.xml
Labels: 🔮 refactor, ❌ remove

#16 Feature/12 login
  build.gradle
  src/main/java/com/spring/moji/config/SecurityConfig.java
  src/main/java/com/spring/moji/controller/HomeController.java
  src/main/java/com/spring/moji/controller/UserController.java
  src/main/java/com/spring/moji/dto/request/LoginRequestDTO.java
  src/main/java/com/spring/moji/entity/CustomerUserEntity.java
  src/main/java/com/spring/moji/entity/UserAuth.java
  src/main/java/com/spring/moji/entity/UserEntity.java
  src/main/java/com/spring/moji/mapper/UserMapper.java
  src/main/java/com/spring/moji/security/CustomerDetailService.java
  src/main/java/com/spring/moji/service/UserService.java
  src/main/java/com/spring/moji/service/UserServiceImpl.java
  src/main/resources/mapper/UserMapper.xml
Labels: 💫feature, BE, FE

#46 [FIX]: user과 권한관련 테이블 스키마 수정
  src/main/resources/SQL/deleteSchema.sql
  src/main/resources/SQL/totalSchema.sql
Labels: ✨chore, BE

#48 [FEAT] Pages 테이블 속성 추가
  src/main/resources/SQL/shema.sql
  src/main/resources/SQL/totalSchema.sql
Labels: 🖋️comment, 💫feature, ❌ remove

#50 [FEAT] 커뮤니티 서비스 관련 REST API 구현
  src/main/java/com/spring/moji/controller/CommunityRestController.java
  src/main/java/com/spring/moji/dto/request/CommunityRequestDTO.java
  src/main/java/com/spring/moji/dto/request/CommunityScrapRequestDTO.java
  src/main/java/com/spring/moji/dto/response/CommunityResponseDTO.java
  src/main/java/com/spring/moji/entity/Scrap.java
  src/main/java/com/spring/moji/mapper/PageMapper.java
  src/main/java/com/spring/moji/mapper/ScrapMapper.java
  src/main/java/com/spring/moji/service/CommunityService.java
  src/main/java/com/spring/moji/service/CommunityServiceImpl.java
  src/main/resources/mapper/PageMapper.xml
  src/main/resources/mapper/ScrapMapper.xml
Labels: 💫feature, BE

#55 [HOTFIX] ScrapMapper resultType경로 수정
  src/main/resources/mapper/ScrapMapper.xml
Labels: 💣 Fix

#56 [FEAT] 다이어리 서비스 조회 페이지 기본 형태 구현
  src/main/java/com/spring/moji/controller/DiaryController.java
  src/main/resources/static/css/content/diary/diary-read.css
  src/main/resources/static/js/content/diary/diary-read.js
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read.jsp
  src/main/webapp/WEB-INF/jsp/page/diary/diary-read-page.jsp
Labels: 💫feature, FE

#53 Feature/42 community page scrap
  src/main/resources/static/css/content/community/diary-gallery.css
  src/main/resources/static/css/content/community/open-diary.css
  src/main/resources/static/image/content/community/filter-icon.png
  src/main/resources/static/image/content/community/full-heart.png
  src/main/resources/static/image/content/community/gray-heart.png
  src/main/resources/static/js/content/community/community-diary.js
  src/main/webapp/WEB-INF/jsp/content/community/community-diary.jsp
Labels: 💫feature, FE

#60 [FEAT] 커뮤니티 공개페이지 목록 조회 비동기 구현
  src/main/resources/static/js/content/community/community-diary.js
  src/main/webapp/WEB-INF/jsp/content/community/community-diary.jsp
Labels: 🖋️comment, 💫feature, FE

#61 [FEAT] REST API 기능 추가 및 스키마 재정의 등 기타사항 리팩토링
  src/main/java/com/spring/moji/controller/DiaryRestController.java
  src/main/java/com/spring/moji/controller/PageRestController.java
  src/main/java/com/spring/moji/dto/request/PageInsertRequestDTO.java
  src/main/java/com/spring/moji/dto/request/PageRequestDTO.java
  src/main/java/com/spring/moji/entity/Diary.java
  src/main/java/com/spring/moji/entity/Page.java
  src/main/java/com/spring/moji/mapper/ImageUrlMapper.java
  src/main/java/com/spring/moji/mapper/LocationMapper.java
  src/main/java/com/spring/moji/mapper/PageMapper.java
  src/main/java/com/spring/moji/service/DiaryService.java
  src/main/java/com/spring/moji/service/DiaryServiceImpl.java
  src/main/java/com/spring/moji/service/PageService.java
  src/main/java/com/spring/moji/service/PageServiceImpl.java
  src/main/java/com/spring/moji/util/S3Util.java
  src/main/resources/SQL/totalSchema.sql
  src/main/resources/mapper/DiaryMapper.xml
  src/main/resources/mapper/ImageUrlMapper.xml
  src/main/resources/mapper/LocationMapper.xml
  src/main/resources/mapper/PageMapper.xml
  src/main/resources/mapper/ScrapMapper.xml
Labels: 🖋️comment, 💫feature, 🔮 refactor, BE

#64 [FEAT] 누락된 InsertRequestDTO 추가 및 스키마 내 제약 구문 정립
  src/main/java/com/spring/moji/dto/request/ImageUrlInsertRequestDTO.java
  src/main/java/com/spring/moji/dto/request/LocationInsertRequestDTO.java
  src/main/resources/SQL/totalSchema.sql
Labels: 💫feature, 💣 Fix, BE

#66 [FE] 필터 모달 css 적용
  src/main/resources/static/css/component/login-modal.css
  src/main/resources/static/css/content/community/open-diary.css
  src/main/resources/static/js/content/community/community-diary.js
  src/main/resources/static/js/content/community/test.js
  src/main/webapp/WEB-INF/jsp/content/community/community-diary.jsp
Labels: 💫feature, 💣 Fix, 😶‍🌫️ rename

#67 [FEAT] 커뮤니티 서비스 페이지 조회/스크랩 기능 추가
  src/main/java/com/spring/moji/controller/CommunityController.java
  src/main/java/com/spring/moji/service/CommunityServiceImpl.java
  src/main/resources/static/js/content/community/community-diary.js
  src/main/resources/static/js/content/community/test.js
  src/main/webapp/WEB-INF/jsp/content/community/community-diary.jsp
Labels: 🖋️comment, 💫feature, ❌ remove, 😶‍🌫️ rename, BE, FE

#70 [FEAT]: 커플 신청기능 구현
  build.gradle
  src/main/java/com/spring/moji/config/JsonConfig.java
  src/main/java/com/spring/moji/config/SecurityConfig.java
  src/main/java/com/spring/moji/controller/CoupleRequestRestController.java
  src/main/java/com/spring/moji/dto/request/UserRequestDTO.java
  src/main/java/com/spring/moji/entity/Request.java
  src/main/java/com/spring/moji/entity/User.java
  src/main/java/com/spring/moji/mapper/RequestMapper.java
  src/main/java/com/spring/moji/mapper/UserMapper.java
  src/main/java/com/spring/moji/security/SignInSuccessHandler.java
  src/main/java/com/spring/moji/service/RequestService.java
  src/main/java/com/spring/moji/service/RequestServiceImpl.java
  src/main/java/com/spring/moji/service/UserService.java
  src/main/java/com/spring/moji/service/UserServiceImpl.java
  src/main/resources/mapper/RequestMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/static/js/content/user/solo-profile.js
  src/main/webapp/WEB-INF/jsp/component/user-info.jsp
  src/main/webapp/WEB-INF/jsp/content/user/solo-profile.jsp
  src/main/webapp/WEB-INF/jsp/page/user/sign-in.jsp
Labels: 💫feature, BE

#73 [FIX] 커뮤니티 이미지 목록 조회- 타입 에러 해결
  src/main/resources/static/js/content/community/community-diary.js
Labels: 💣 Fix, FE

#75 [Front]: layout front 수정
  src/main/resources/static/css/common/layout.css
  src/main/resources/static/css/content/diary/diary-read.css
  src/main/resources/static/image/common/couple.jpg
  src/main/resources/static/image/common/diaryLogo.png
  src/main/resources/static/image/common/logo.jpg
  src/main/resources/static/image/common/profileSolo.png
  src/main/resources/static/js/common/layout.js
  src/main/resources/static/template/layout.jsp
  src/main/webapp/WEB-INF/jsp/layout/layout.jsp
Labels: 🔮 refactor, FE

#76 [FE] 필터 모달 radius 슬라이더 업데이트 로직 추가
  src/main/resources/static/css/component/login-modal.css
  src/main/resources/static/css/content/community/open-diary.css
  src/main/resources/static/js/content/community/community-diary.js
  src/main/webapp/WEB-INF/jsp/component/login-modal.jsp
  src/main/webapp/WEB-INF/jsp/content/community/community-diary.jsp
Labels: 🖋️comment, 💫feature, FE

#78 [feat]: layout background css수정
  src/main/resources/static/css/common/layout.css
Labels: 🔮 refactor, FE

#81 [feat]: layout security 추가
  src/main/resources/static/template/layout.jsp
  src/main/webapp/WEB-INF/jsp/layout/layout.jsp
Labels: 💫feature

#82 [feat]: layout background수정
  src/main/resources/static/css/common/layout.css
  src/main/resources/static/css/component/login-modal.css
  src/main/webapp/WEB-INF/jsp/layout/layout.jsp
Labels: FE

#84 [FEAT] 커뮤니티 조회 서비스 내 기능 추가
  src/main/java/com/spring/moji/controller/DiaryRestController.java
  src/main/resources/static/css/content/diary/diary-read.css
  src/main/resources/static/image/content/diary/delete-page.png
  src/main/resources/static/image/content/diary/diary-cover.png
  src/main/resources/static/image/content/diary/hide-page.png
  src/main/resources/static/image/content/diary/show-page.png
  src/main/resources/static/js/content/diary/diary-read.js
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read.jsp
Labels: 🖋️comment, 💫feature, BE, FE

#87 [FEAT] 다이어리 표지 image 추가
  src/main/resources/static/image/content/diary/diary-cover.png
Labels: 😶‍🌫️ rename, FE

#88 [FE] 커뮤니티 페이지 일기 css 수정
  src/main/resources/static/css/component/login-modal.css
  src/main/resources/static/css/content/community/open-diary.css
  src/main/resources/static/image/common/color-no-image.png
  src/main/resources/static/image/common/no-image.png
  src/main/resources/static/js/content/community/community-diary.js
  src/main/webapp/WEB-INF/jsp/content/community/community-diary.jsp
Labels: 💫feature, FE

#90 Feat/69 front layout
  src/main/resources/static/css/content/community/diary-gallery.css
  src/main/resources/static/css/content/diary/diary-read.css
  src/main/resources/static/js/content/community/community-diary.js
  src/main/resources/static/js/content/diary/diary-read.js
Labels: FE

#93 [feat]: 다이어리 css수정
  src/main/resources/static/css/content/diary/diary-read.css
Labels: FE

#94 [FE] 커뮤니티 및 다이어리 페이지 css 수정
  src/main/resources/static/js/content/community/community-diary.js
  src/main/resources/static/js/content/diary/diary-read.js
Labels: 💣 Fix, 😶‍🌫️ rename, ⭐sytle, FE

#97 [FEAT] 다이어리 페이지 조회 애니메이션 수정 / 커뮤니티 REST API 기능 추가
  src/main/java/com/spring/moji/controller/CommunityRestController.java
  src/main/java/com/spring/moji/mapper/ScrapMapper.java
  src/main/java/com/spring/moji/service/CommunityService.java
  src/main/java/com/spring/moji/service/CommunityServiceImpl.java
  src/main/resources/mapper/ScrapMapper.xml
  src/main/resources/static/js/content/diary/diary-read.js
Labels: 💫feature, BE, FE

#99 [Front] 다이어리 쓰기 front 수정
  src/main/resources/static/css/common/layout.css
  src/main/resources/static/css/content/diary/diary-read.css
  src/main/resources/static/css/content/diary/diary-write.css
  src/main/resources/static/js/content/diary/diary-write.js
  src/main/webapp/WEB-INF/jsp/content/diary/diary-write.jsp
  src/main/webapp/WEB-INF/jsp/layout/layout.jsp
Labels: 💫feature, FE

#101 [FE] 커뮤니티 -하단 스크랩 실시간 조회 css
  src/main/resources/static/css/common/layout.css
  src/main/resources/static/css/content/community/diary-gallery.css
  src/main/resources/static/css/content/community/open-diary.css
  src/main/resources/static/js/content/community/community-diary.js
  src/main/webapp/WEB-INF/jsp/content/community/community-diary.jsp
Labels: 🖋️comment, 💫feature, ❌ remove, 😶‍🌫️ rename, FE

#103 [FEAT] 맵 서비스를 위한 REST API 기능 구현
  src/main/java/com/spring/moji/controller/MapRestController.java
  src/main/java/com/spring/moji/dto/request/MapRequestDTO.java
  src/main/java/com/spring/moji/entity/Location.java
  src/main/java/com/spring/moji/mapper/LocationMapper.java
  src/main/java/com/spring/moji/mapper/PageMapper.java
  src/main/java/com/spring/moji/service/DiaryServiceImpl.java
  src/main/java/com/spring/moji/service/MapService.java
  src/main/java/com/spring/moji/service/MapServiceImpl.java
  src/main/resources/mapper/LocationMapper.xml
  src/main/resources/mapper/PageMapper.xml
Labels: 💫feature, 💣 Fix, BE

#105 [FE] 커뮤니티 - 스크랩 갯수 조회 api 및 세션 적용
  src/main/resources/static/js/content/community/community-diary.js
  src/main/webapp/WEB-INF/jsp/content/community/community-diary.jsp
Labels: 💫feature, FE

#107 Feature/106 fe apply session to diary
  src/main/resources/static/css/content/community/community-diary.css
  src/main/resources/static/js/content/community/community-diary.js
  src/main/resources/static/js/content/diary/diary-read.js
  src/main/resources/static/js/content/diary/diary-write.js
  src/main/webapp/WEB-INF/jsp/content/community/community-diary.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/diary-write.jsp
Labels: 🖋️comment, 🔮 refactor, BE, FE

#108 Feat/100 front diary-right front
  src/main/resources/static/css/common/layout.css
  src/main/resources/static/css/content/diary/diary-read.css
  src/main/resources/static/css/content/diary/diary-write.css
  src/main/resources/static/image/content/diary/write.png
  src/main/resources/static/js/content/community/community-diary.js
  src/main/resources/static/js/content/diary/diary-read.js
  src/main/resources/static/js/content/diary/diary-write.js
  src/main/resources/static/js/content/diary/write-diary.js
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/diary-write.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/read-diary.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/second-page.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/toolbar.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/write-diary.jsp
Labels: ❌ remove, FE

#109 [Feat]: layout dropdown 추가
  src/main/webapp/WEB-INF/jsp/layout/layout.jsp
Labels: FE

#111 Feat/100 front diary right front
  src/main/resources/static/css/content/diary/diary-write.css
  src/main/resources/static/js/content/diary/diary-read.js
  src/main/resources/static/js/content/diary/diary-write.js
Labels: 💣 Fix, BE

#113 Feat/100 front diary right front
  src/main/resources/static/css/content/diary/diary-read.css
  src/main/resources/static/js/content/diary/diary-read.js
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read.jsp
Labels: 💣 Fix, FE

#114 [Feat]: 다이어리 커뮤니티 css 조회와 통일
  src/main/resources/static/css/content/community/community-diary.css
Labels: FE

#115 [FE] 다이어리 css 수정 및 이미지 삭제 api 연동
  src/main/resources/static/css/content/diary/diary-write.css
  src/main/resources/static/js/content/diary/diary-read.js
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read.jsp
Labels: 💫feature, 💣 Fix, 🔮 refactor, FE

#117 [FEAT] 맵 서비스 기능 구현
  src/main/java/com/spring/moji/controller/MapController.java
  src/main/java/com/spring/moji/controller/MapRestController.java
  src/main/java/com/spring/moji/mapper/PageMapper.java
  src/main/java/com/spring/moji/service/CommunityServiceImpl.java
  src/main/java/com/spring/moji/service/DiaryServiceImpl.java
  src/main/java/com/spring/moji/service/MapServiceImpl.java
  src/main/resources/mapper/PageMapper.xml
  src/main/resources/static/css/content/map/map-read.css
  src/main/resources/static/js/content/map/map-read.js
  src/main/webapp/WEB-INF/jsp/content/map/map-read.jsp
  src/main/webapp/WEB-INF/jsp/page/map/map-read-page.jsp
Labels: 💫feature, 💣 Fix, BE, FE

#119 Update README.md
  README.md
Labels: ⭐sytle

#120 Update README.md
  README.md
Labels: ⭐sytle

#122 [FE] 유저 권한에 따른 '다이어리'탭 hidden처리 및 sidebar 사진 수정
  src/main/resources/static/css/content/diary/diary-write.css
  src/main/webapp/WEB-INF/jsp/layout/layout.jsp
Labels: 🔮 refactor, FE

#125 [FIX] layout.css 수정
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read.jsp
  src/main/webapp/WEB-INF/jsp/layout/layout.jsp
Labels: 💣 Fix, 🔮 refactor, FE

#123 [FIX]: 회원가입 시 발생하는 오류 해결
  src/main/java/com/spring/moji/controller/HomeController.java
  src/main/java/com/spring/moji/service/UserService.java
  src/main/java/com/spring/moji/service/UserServiceImpl.java
  src/main/resources/static/css/content/diary/diary-write.css
  src/main/resources/static/js/content/user/email-verification.js
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read.jsp
  src/main/webapp/WEB-INF/jsp/page/user/sign-up.jsp
Labels: 💣 Fix, BE

#126 Feat/100 front diary right front
  src/main/webapp/WEB-INF/jsp/layout/layout.jsp
Labels: FE

#127 [FIX] 프론트/백엔드 코드 내 버그 수정
  src/main/resources/mapper/DiaryMapper.xml
  src/main/resources/static/js/content/community/community-diary.js
  src/main/resources/static/js/content/diary/diary-read.js
  src/main/resources/static/js/content/diary/diary-write.js
  src/main/webapp/WEB-INF/jsp/content/diary/diary-read.jsp
  src/main/webapp/WEB-INF/jsp/content/diary/diary-write.jsp
Labels: 🖋️comment, 💫feature, 💣 Fix, BE, FE

#130 [FEAT] 맵 서비스 등록 및 연결 확인
  src/main/resources/static/js/content/map/map-read.js
  src/main/webapp/WEB-INF/jsp/content/map/map-read.jsp
  src/main/webapp/WEB-INF/jsp/layout/layout.jsp
Labels: 💫feature, FE

#132 Feat/100 front diary right front
  src/main/resources/static/js/content/diary/diary-read.js
  src/main/webapp/WEB-INF/jsp/page/user/sign-in.jsp
Labels: BE

#137 [FIX]: 로그아웃을 해도 세션이 남아있는 문제 해결
  src/main/java/com/spring/moji/config/SecurityConfig.java
  src/main/java/com/spring/moji/controller/HomeController.java
Labels: 💫feature, BE

#138 [FE] 이미지 버튼 비활성화 처리(다이어리,
  src/main/resources/static/js/content/community/community-diary.js
  src/main/resources/static/js/content/diary/diary-read.js
Labels: 🖋️comment, 💫feature, 💣 Fix, FE
